{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "script": ["npm run test"],
  "node_js": "8",
  "language": "node_js",
  "after_success":
    ["npm install --save-dev coveralls", "npm run coveralls", "npm pack"],
  "before_script": ["npm install"],
}
